item {
  name: "김밥"
  id: 1
}
item {
  name: "제육덮밥"
  id: 2
}
item {
  name: "초밥"
  id: 3
}
item {
  name: "돌솥비빔밥"
  id: 4
}
item {
  name: "유부초밥"
  id: 5
}
item {
  name: "회덮밥"
  id: 6
}
item {
  name: "쌀밥"
  id: 7
}
item {
  name: "kong-bab"
  id: 8
}
item {
  name: "잡곡밥"
  id: 9
}
item {
  name: "새우볶음밥"
  id: 10
}
item {
  name: "김치볶음밥"
  id: 11
}
item {
  name: "카레라이스"
  id: 12
}
item {
  name: "주먹밥"
  id: 13
}
item {
  name: "불고기덮밥"
  id: 14
}
item {
  name: "잡채덮밥"
  id: 15
}
item {
  name: "육회비빔밥"
  id: 16
}
item {
  name: "순대국밥"
  id: 17
}
item {
  name: "낫토"
  id: 18
}
item {
  name: "물냉면"
  id: 19
}
item {
  name: "라면"
  id: 20
}
item {
  name: "수제비"
  id: 21
}
item {
  name: "잡채"
  id: 22
}
item {
  name: "칼국수"
  id: 23
}
item {
  name: "콩국수"
  id: 24
}
item {
  name: "쌀국수"
  id: 25
}
item {
  name: "파스타(토마토)"
  id: 26
}
item {
  name: "우동"
  id: 27
}
item {
  name: "짜장면"
  id: 28
}
item {
  name: "짬뽕"
  id: 29
}
item {
  name: "비빔냉면"
  id: 30
}
item {
  name: "딤섬"
  id: 31
}
item {
  name: "물만두"
  id: 32
}
item {
  name: "군만두"
  id: 33
}
item {
  name: "떡국(만두국)"
  id: 34
}
item {
  name: "미역국"
  id: 35
}
item {
  name: "북어국"
  id: 36
}
item {
  name: "육개장"
  id: 37
}
item {
  name: "뼈다귀해장국"
  id: 38
}
item {
  name: "콩나물해장국"
  id: 39
}
item {
  name: "된장국"
  id: 40
}
item {
  name: "갈비탕"
  id: 41
}
item {
  name: "감자탕"
  id: 42
}
item {
  name: "닭볶음탕"
  id: 43
}
item {
  name: "매운탕"
  id: 44
}
item {
  name: "삼계탕"
  id: 45
}
item {
  name: "홍합탕"
  id: 46
}
item {
  name: "어묵탕"
  id: 47
}
item {
  name: "haemul-tang"
  id: 48
}
item {
  name: "김치찌개"
  id: 49
}
item {
  name: "동태찌개"
  id: 50
}
item {
  name: "된장찌개"
  id: 51
}
item {
  name: "부대찌개"
  id: 52
}
item {
  name: "순두부찌개"
  id: 53
}
item {
  name: "청국장찌개"
  id: 54
}
item {
  name: "버섯(불고기)전골"
  id: 55
}
item {
  name: "곱창전골"
  id: 56
}
item {
  name: "만두전골"
  id: 57
}
item {
  name: "비지찌개"
  id: 58
}
item {
  name: "꼬치"
  id: 59
}
item {
  name: "닭갈비"
  id: 60
}
item {
  name: "떡갈비"
  id: 61
}
item {
  name: "불고기"
  id: 62
}
item {
  name: "삼겹살"
  id: 63
}
item {
  name: "연어스테이크"
  id: 64
}
item {
  name: "장어구이"
  id: 65
}
item {
  name: "고등어구이"
  id: 66
}
item {
  name: "갈치구이"
  id: 67
}
item {
  name: "곱창구이"
  id: 68
}
item {
  name: "돼지갈비"
  id: 69
}
item {
  name: "새우구이"
  id: 70
}
item {
  name: "오리구이"
  id: 71
}
item {
  name: "전복구이"
  id: 72
}
item {
  name: "ansim-seuteikeu"
  id: 73
}
item {
  name: "막창구이"
  id: 74
}
item {
  name: "치즈등갈비"
  id: 75
}
item {
  name: "낙지호롱"
  id: 76
}
item {
  name: "장조림"
  id: 77
}
item {
  name: "감자조림"
  id: 78
}
item {
  name: "godeungeo-jorim"
  id: 79
}
item {
  name: "galchi-jorim"
  id: 80
}
item {
  name: "콩자반"
  id: 81
}
item {
  name: "우엉조림"
  id: 82
}
item {
  name: "연근조림"
  id: 83
}
item {
  name: "두부조림"
  id: 84
}
item {
  name: "계란장조림"
  id: 85
}
item {
  name: "떡볶이"
  id: 86
}
item {
  name: "제육볶음(돼지두루치기)"
  id: 87
}
item {
  name: "멸치볶음"
  id: 88
}
item {
  name: "가지볶음"
  id: 89
}
item {
  name: "소세지야채볶음"
  id: 90
}
item {
  name: "감자(채)볶음"
  id: 91
}
item {
  name: "낙지(쭈꾸미)볶음"
  id: 92
}
item {
  name: "닭발"
  id: 93
}
item {
  name: "건새우볶음"
  id: 94
}
item {
  name: "콘치즈"
  id: 95
}
item {
  name: "감바스"
  id: 96
}
item {
  name: "치킨"
  id: 97
}
item {
  name: "돈가스"
  id: 98
}
item {
  name: "탕수육"
  id: 99
}
item {
  name: "새우튀김"
  id: 100
}
item {
  name: "고구마맛탕"
  id: 101
}
item {
  name: "감자튀김"
  id: 102
}
item {
  name: "핫도그"
  id: 103
}
item {
  name: "빈대떡(녹두)"
  id: 104
}
item {
  name: "오꼬노미야끼"
  id: 105
}
item {
  name: "타코야끼"
  id: 106
}
item {
  name: "파전"
  id: 107
}
item {
  name: "계란말이"
  id: 108
}
item {
  name: "﻿(애)호박전"
  id: 109
}
item {
  name: "두부부침"
  id: 110
}
item {
  name: "김치전"
  id: 111
}
item {
  name: "감자전"
  id: 112
}
item {
  name: "갈비찜"
  id: 113
}
item {
  name: "계란찜"
  id: 114
}
item {
  name: "순대"
  id: 115
}
item {
  name: "족발"
  id: 116
}
item {
  name: "아구(귀)찜"
  id: 117
}
item {
  name: "찜닭"
  id: 118
}
item {
  name: "조개찜"
  id: 119
}
item {
  name: "깍두기"
  id: 120
}
item {
  name: "배추김치"
  id: 121
}
item {
  name: "파김치"
  id: 122
}
item {
  name: "오이소박이"
  id: 123
}
item {
  name: "부추김치"
  id: 124
}
item {
  name: "동치미"
  id: 125
}
item {
  name: "알타리(총각)김치"
  id: 126
}
item {
  name: "갓김치"
  id: 127
}
item {
  name: "간장게장"
  id: 128
}
item {
  name: "새우젓"
  id: 129
}
item {
  name: "간장새우"
  id: 130
}
item {
  name: "양념게장"
  id: 131
}
item {
  name: "샐러드"
  id: 132
}
item {
  name: "소보로빵"
  id: 133
}
item {
  name: "꽈배기"
  id: 134
}
item {
  name: "머핀"
  id: 135
}
item {
  name: "팥죽"
  id: 136
}
item {
  name: "전복죽"
  id: 137
}
item {
  name: "호박죽"
  id: 138
}
item {
  name: "야채죽"
  id: 139
}
item {
  name: "도넛츠"
  id: 140
}
item {
  name: "찐빵"
  id: 141
}
item {
  name: "바게트"
  id: 142
}
item {
  name: "크로와상"
  id: 143
}
item {
  name: "소시지빵"
  id: 144
}
item {
  name: "빙수"
  id: 145
}
item {
  name: "티라미수"
  id: 146
}
item {
  name: "양파장아찌"
  id: 147
}
item {
  name: "마늘장아찌"
  id: 148
}
item {
  name: "무말랭이"
  id: 149
}
item {
  name: "열무김치"
  id: 150
}
item {
  name: "콩나물무침"
  id: 151
}
item {
  name: "오므라이스"
  id: 152
}
item {
  name: "곰탕(설렁탕)"
  id: 153
}
item {
  name: "김"
  id: 154
}
item {
  name: "오징어볶음"
  id: 155
}
item {
  name: "오징어젓갈"
  id: 156
}
item {
  name: "마들렌"
  id: 157
}
item {
  name: "롤케이크"
  id: 158
}
item {
  name: "단무지"
  id: 159
}
item {
  name: "깻잎장아찌"
  id: 160
}
item {
  name: "강정"
  id: 161
}
item {
  name: "와플"
  id: 162
}
item {
  name: "호떡"
  id: 163
}
item {
  name: "샌드위치"
  id: 164
}
item {
  name: "붕어빵"
  id: 165
}
item {
  name: "호두과자"
  id: 166
}
item {
  name: "송편"
  id: 167
}
item {
  name: "유과"
  id: 168
}
item {
  name: "꿀떡"
  id: 169
}
item {
  name: "절편"
  id: 170
}
item {
  name: "찹쌀떡"
  id: 171
}
item {
  name: "마카롱"
  id: 172
}
item {
  name: "나초"
  id: 173
}
item {
  name: "버터쿠키"
  id: 174
}
item {
  name: "피자"
  id: 175
}
item {
  name: "생선회"
  id: 176
}
item {
  name: "육회"
  id: 177
}
item {
  name: "문어숙회"
  id: 178
}
item {
  name: "굴회"
  id: 179
}
item {
  name: "버섯볶음"
  id: 180
}
item {
  name: "닭가슴살구이"
  id: 181
}
item {
  name: "동그랑땡"
  id: 182
}
item {
  name: "미역줄기볶음"
  id: 183
}
item {
  name: "도토리묵"
  id: 184
}
item {
  name: "어묵볶음"
  id: 185
}
item {
  name: "김말이"
  id: 186
}
item {
  name: "고구마"
  id: 187
}
item {
  name: "햄버거"
  id: 188
}
item {
  name: "흑미밥"
  id: 189
}
item {
  name: "크림파스타"
  id: 190
}
item {
  name: "오이무침"
  id: 191
}
item {
  name: "팥빙수"
  id: 192
}
item {
  name: "상추"
  id: 193
}
item {
  name: "시금치무침"
  id: 194
}
item {
  name: "소고기무국"
  id: 195
}
item {
  name: "수육"
  id: 196
}
item {
  name: "쌈장"
  id: 197
}
item {
  name: "계란후라이"
  id: 198
}
item {
  name: "hyeonmibab"
  id: 199
}
item {
  name: "소세지부침"
  id: 200
}
